import HautevilleHouse.FamiliesModuliSpacesArithmeticNonCanonicalLaneLean.AdmissibleClass
import HautevilleHouse.FamiliesModuliSpacesArithmeticNonCanonicalLaneLean.BridgeLemmas
import HautevilleHouse.FamiliesModuliSpacesArithmeticNonCanonicalLaneLean.GateLemmas
import HautevilleHouse.FamiliesModuliSpacesArithmeticNonCanonicalLaneLean.FinalTheorem
import HautevilleHouse.FamiliesModuliSpacesArithmeticNonCanonicalLaneLean.MathlibObjects
import HautevilleHouse.FamiliesModuliSpacesArithmeticNonCanonicalLaneLean.MathlibStatement
import HautevilleHouse.FamiliesModuliSpacesArithmeticNonCanonicalLaneLean.Noncollapsing
import HautevilleHouse.FamiliesModuliSpacesArithmeticNonCanonicalLaneLean.PerelmanAnalyticEvidenceTerms
import HautevilleHouse.FamiliesModuliSpacesArithmeticNonCanonicalLaneLean.PerelmanAnalyticProof

-- Root module for Families Moduli Spaces Arithmetic Non Canonical Lane Lean
namespace HautevilleHouse
namespace FamiliesModuliSpacesArithmeticNonCanonicalLaneLean

theorem domain_endgame (A : AdmissibleClass) : ConstrainedFamiliesModuliSpacesArithmeticNonClosure A :=
  constrained_families_moduli_spaces_arithmetic_non_endgame A

end FamiliesModuliSpacesArithmeticNonCanonicalLaneLean
end HautevilleHouse